import { Image } from 'react-native';
import { Feeds_Icon, Home_Icon, Matches_Icon, Mess_Icon } from './assets/Images';
import Matches from './screens/app/Matches';

export const TopUsers = [
  {
    img: require('./assets/Images/Icons/tp0.png'),
  },
  {
    img: require('./assets/Images/Icons/tp1.png'),
  },
  {
    img: require('./assets/Images/Icons/tp2.png'),
  },
  {
    img: require('./assets/Images/Icons/tp3.png'),
  },
  {
    img: require('./assets/Images/Icons/tp4.png'),
  },
  {
    img: require('./assets/Images/Icons/tp1.png'),
  },
  {
    img: require('./assets/Images/Icons/tp2.png'),
  },
  {
    img: require('./assets/Images/Icons/tp3.png'),
  },
  {
    img: require('./assets/Images/Icons/tp4.png'),
  },
];

export const Explore = [
  {
    img: require('./assets/Images/Icons/Ex1.png'),
    name: 'William H. Jenkins, 26',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F1.png'),
    Gift: false,
    Elli:require("./assets/Images/Icons/E.png"),
    gift: require('./assets/Images/Icons/gift.png'),
    Ell:true,
    gN:"26",
  },
  {
    img: require('./assets/Images/Icons/Ex2.png'),
    name: 'William H. Jenkins, 27',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F2.png'),
    Gift: false,
    gift: require('./assets/Images/Icons/gift.png'),
    Elli:require("./assets/Images/Icons/E.png"),
    Ell:false,
    gN:"26",
  },
  {
    img: require('./assets/Images/Icons/Ex3.png'),
    name: 'William H. Jenkins, 26',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F2.png'),
    Gift: true,
    gift: require('./assets/Images/Icons/gift.png'),
    Elli:require("./assets/Images/Icons/E.png"),
    Ell:true,
    gN:"26",
  }, 
  {
    img: require('./assets/Images/Icons/Ex1.png'),
    name: 'William H. Jenkins, 26',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F1.png'),
    Gift: false,
    Elli:require("./assets/Images/Icons/E.png"),
    gift: require('./assets/Images/Icons/gift.png'),
    Ell:true,
    gN:"26",
  },
  {
    img: require('./assets/Images/Icons/Ex2.png'),
    name: 'William H. Jenkins, 27',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F2.png'),
    Gift: false,
    gift: require('./assets/Images/Icons/gift.png'),
    Elli:require("./assets/Images/Icons/E.png"),
    Ell:false,
    gN:"26",
  },
  {
    img: require('./assets/Images/Icons/Ex3.png'),
    name: 'William H. Jenkins, 26',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F2.png'),
    Gift: true,
    gift: require('./assets/Images/Icons/gift.png'),
    Elli:require("./assets/Images/Icons/E.png"),
    Ell:true,
    gN:"26",
  }, 
  {
    img: require('./assets/Images/Icons/Ex1.png'),
    name: 'William H. Jenkins, 26',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F1.png'),
    Gift: false,
    Elli:require("./assets/Images/Icons/E.png"),
    gift: require('./assets/Images/Icons/gift.png'),
    Ell:true,
    gN:"26",
  },
  {
    img: require('./assets/Images/Icons/Ex2.png'),
    name: 'William H. Jenkins, 27',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F2.png'),
    Gift: false,
    gift: require('./assets/Images/Icons/gift.png'),
    Elli:require("./assets/Images/Icons/E.png"),
    Ell:false,
    gN:"26",
  },
  {
    img: require('./assets/Images/Icons/Ex3.png'),
    name: 'William H. Jenkins, 26',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F2.png'),
    Gift: true,
    gift: require('./assets/Images/Icons/gift.png'),
    Elli:require("./assets/Images/Icons/E.png"),
    Ell:true,
    gN:"26",
  }, 
  {
    img: require('./assets/Images/Icons/Ex1.png'),
    name: 'William H. Jenkins, 26',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F1.png'),
    Gift: false,
    Elli:require("./assets/Images/Icons/E.png"),
    gift: require('./assets/Images/Icons/gift.png'),
    Ell:true,
    gN:"26",
  },
  {
    img: require('./assets/Images/Icons/Ex2.png'),
    name: 'William H. Jenkins, 27',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F2.png'),
    Gift: false,
    gift: require('./assets/Images/Icons/gift.png'),
    Elli:require("./assets/Images/Icons/E.png"),
    Ell:false,
    gN:"26",
  },
  {
    img: require('./assets/Images/Icons/Ex3.png'),
    name: 'William H. Jenkins, 26',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F2.png'),
    Gift: true,
    gift: require('./assets/Images/Icons/gift.png'),
    Elli:require("./assets/Images/Icons/E.png"),
    Ell:true,
    gN:"26",
  }, 
  {
    img: require('./assets/Images/Icons/Ex1.png'),
    name: 'William H. Jenkins, 26',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F1.png'),
    Gift: false,
    Elli:require("./assets/Images/Icons/E.png"),
    gift: require('./assets/Images/Icons/gift.png'),
    Ell:true,
    gN:"26",
  },
  {
    img: require('./assets/Images/Icons/Ex2.png'),
    name: 'William H. Jenkins, 27',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F2.png'),
    Gift: false,
    gift: require('./assets/Images/Icons/gift.png'),
    Elli:require("./assets/Images/Icons/E.png"),
    Ell:false,
    gN:"26",
  },
  {
    img: require('./assets/Images/Icons/Ex3.png'),
    name: 'William H. Jenkins, 26',
    distance: '1.3km away',
    flag: require('./assets/Images/Icons/F2.png'),
    Gift: true,
    gift: require('./assets/Images/Icons/gift.png'),
    Elli:require("./assets/Images/Icons/E.png"),
    Ell:true,
    gN:"26",
  }, 
];
export const BottomTabsIcons = Color => [
    <Home_Icon Color={Color} />,
  
    <Matches_Icon Color={Color} />,
    <Feeds_Icon Color={Color} />,
    <Mess_Icon Color={Color} />,
    <Image
    style={{
    //   tintColor: Color ? Color : 'black',
    height:40,width:40
    }}
    source={require("./assets/Images/Icons/Pro.png")}
  />,
  ];